/**
 * Maps each room to the weapons that could plausibly be *found* there.
 * Weapons and rooms are assigned independently at game time - the fun is
 * in the mismatch (e.g. kill someone in the garden using a rubber duck).
 */
export const ROOM_WEAPONS: Readonly<Record<string, readonly string[] | undefined>> = {
  Kitchen: [
    "a frying pan",
    "a wooden spoon",
    "a rolling pin",
    "a wine bottle",
    "a tea towel",
    "a mug",
    "a teapot or cafetière",
    "an eggcup",
    "a pot or pan",
    "some butter",
    "a piece of fruit",
    "a jug of water",
    "a colander",
    "a spatula",
  ],
  Bathroom: [
    "a bar of soap",
    "a loo roll",
    "a toothbrush",
    "a rubber duck",
    "a flannel",
    "a shower cap",
    "a loofa",
  ],
  Bedroom: [
    "a pillow",
    "a book",
    "a pair of spectacles",
    "a multicoloured sock",
    "a phone charger",
    "a coat hanger",
    "a bedside lamp",
  ],
  "Living Room": [
    "a cushion",
    "a TV remote",
    "a book",
    "a phone charger",
    "a bracelet",
    "a coaster",
    "a credit or debit card",
  ],
  "Dining Room": [
    "a napkin",
    "a wine bottle",
    "a candle",
    "a place mat",
    "a salt shaker",
    "a pepper grinder",
  ],
  "Games Room": [
    "a playing card",
    "a die",
    "a chess piece",
    "a ping pong ball",
    "a pool cue",
    "a board game box",
  ],
  Garden: [
    "a garden glove",
    "a trowel",
    "a watering can",
    "a plant pot",
    "a garden fork",
    "a kneeling pad",
  ],
  Hallway: [
    "an umbrella",
    "a coat hanger",
    "a door key",
    "a scarf",
    "a welcome mat",
  ],
  Garage: [
    "a screwdriver",
    "a torch",
    "a broom",
    "a paint roller",
    "a spirit level",
  ],
  Patio: [
    "a garden chair",
    "a plant pot",
    "a citronella candle",
    "a pair of BBQ tongs",
    "an outdoor cushion",
  ],
  "Hot Tub": [
    "a rubber duck",
    "a pool noodle",
    "a towel",
    "a floating drinks holder",
  ],
  Stairs: [
    "a lightbulb",
    "a notebook",
    "a paper chicken",
    "a shoe",
    "a sock",
  ],
  "Utility Room": [
    "a mop",
    "a sponge",
    "a laundry basket",
    "a clothes peg",
    "a dustpan",
  ],
  Study: [
    "a stapler",
    "a pen",
    "a notebook",
    "a rubber band",
    "a ruler",
    "a paperclip",
  ],
};

export const DEFAULT_ROOMS: readonly string[] = [
  "Kitchen",
  "Living Room",
  "Bathroom",
  "Bedroom",
  "Garden",
  "Hallway",
  "Dining Room",
  "Stairs",
];
